version: '3.8'

networks:
  vidasalud-apps-net:
    driver: bridge

services:

  ms-bff:
    build:
      context: ./ms-bff
      dockerfile: Dockerfile
    container_name: ms-bff
    restart: always
    ports:
      - "18080:18080"
    environment:
      - SERVER_PORT=18080
      - SERVICES_APPOINTMENTS_URL=http://ms-appointments:8081
      - SERVICES_CATALOG_URL=http://ms-catalog:8082
      - SERVICES_REPORT_URL=http://ms-report:8083
      - SERVICES_AUDIT_URL=http://ms-audit:8084
    depends_on:
      - ms-catalog
      - ms-appointments
    networks:
      - vidasalud-apps-net

  ms-catalog:
    build:
      context: ./ms-catalog
      dockerfile: Dockerfile
    container_name: ms-catalog
    restart: always
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
      - SPRING_DATASOURCE_URL=jdbc:mysql://172.31.70.67:3306/bd_catalog?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    networks:
      - vidasalud-apps-net

  ms-appointments:
    build:
      context: ./ms-appointment
      dockerfile: Dockerfile
    container_name: ms-appointments
    restart: always
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:mysql://172.31.70.67:3306/bd_appointments?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_RABBITMQ_HOST=172.31.64.175
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=172.31.77.176:9092
      - SERVICES_CATALOG_URL=http://ms-catalog:8082
    networks:
      - vidasalud-apps-net

  ms-notify:
    build:
      context: ./ms-notify
      dockerfile: Dockerfile
    container_name: ms-notify
    restart: always
    environment:
      - SERVER_PORT=8085
      - SPRING_RABBITMQ_HOST=172.31.64.175
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_AUTOCONFIGURE_EXCLUDE=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    networks:
      - vidasalud-apps-net

  ms-report:
    build:
      context: ./ms-report
      dockerfile: Dockerfile
    container_name: ms-report
    restart: always
    ports:
      - "8083:8083"
    environment:
      - SERVER_PORT=8083
      - SPRING_DATASOURCE_URL=jdbc:mysql://172.31.70.67:3306/bd_report?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=172.31.77.176:9092
    networks:
      - vidasalud-apps-net

  ms-audit:
    build:
      context: ./ms-audit
      dockerfile: Dockerfile
    container_name: ms-audit
    restart: always
    ports:
      - "8084:8084"
    environment:
      - SERVER_PORT=8084
      - SPRING_DATASOURCE_URL=jdbc:mysql://172.31.70.67:3306/bd_audit?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=172.31.77.176:9092
    networks:
      - vidasalud-apps-net