spring.application.name=ms-bff

#configurar despues variable de entorno
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/${id_inquilino:tenant_ID}/v2.0

#se debe cambiar por la ip del ec2
appointments.url=http://localhost:8081 
catalog.url=http://localhost:8082