spring.application.name=ms-bff

#configurar despues variable de entorno
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/03bb15ff-2ba9-4e00-8ebd-10c0986f5c28/v2.0

#se debe cambiar por la ip del ec2
appointments.url=http://localhost:8081 
catalog.url=http://localhost:8082